### ISSUE TITLE
Add new table using HTML and CSS.

### ISSUE THREAD

**Issue by sahilsingh7735** [sahilsingh7735/web#1]
Make a style.css file and import in HTML and make a simple table using HTML and CSS, the UI should be good.

**Comment by ankitgauri26** [comment]
@sahilsingh7735  - Please provide some more details i.e where to add new table, what will be the columns, what data to be shown. Happy to work

**Comment by sahilsingh7735** [comment]
@ankitgauri26  Add some dynamic table at the center of page ,using button the table should be automatically generated web page .

**Comment by ParthasarathiMahana** [comment]
Hi [sahil](https://github.com/sahilsingh7735) ,I will be happy to contribute to your issue. Is it still open?

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana  sure go ahead.

**Comment by ParthasarathiMahana** [comment]
@sahilsingh7735 Thank you, Can you please describe more on what should I exactly do?

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana may I know are you beginner ?? So I will make a simple task for you.

**Comment by ParthasarathiMahana** [comment]
@sahilsingh7735  Yes sir, I am a beginner.

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana I have added new issue you work on that is very easy

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana message me on new issue i will assign you that.

**Comment by ParthasarathiMahana** [comment]
Ok@sahilsingh7735  Thank you

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana welcome
