### ISSUE TITLE
Make separate folder for CSS and import in HTML file.

### ISSUE THREAD

**Issue by sahilsingh7735** [sahilsingh7735/web#10]
Make a separate folder and make a Style.css file and using this file in HTML page,

1. Make H1 tag and write "Welcome to seven wonders of the world"
2. There should be a good background of seven wonders of the world.

**Comment by ParthasarathiMahana** [comment]
Hi @sahilsingh7735  Is this the issue you are talking about?

**Comment by harsitagarwalla187** [comment]
Hi! Can i work in this issue?

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana yes

**Comment by sahilsingh7735** [comment]
@harsitagarwalla187 I will make a different task for you if you want this task is assigned to @ParthasarathiMahana.
@harsitagarwalla187 may I know are you beginner or experience?? So I will make a different task for you. If you want.

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana you can see this resource [See This](https://www.w3schools.com/html/html_tables.asp)
[For CSS](https://www.thoughtco.com/css-and-notepad-created-web-page-3466582)

**Comment by ParthasarathiMahana** [comment]
ok, Thanks @sahilsingh7735

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana Welcome,

**Comment by Dani-Google** [comment]
Hi
Im new here and would love to contribute... Can you assign to me?

**Comment by Dani-Google** [comment]
Hi @sahilsingh7735 
Im new here and would love to contribute... Can you assign to me?

**Comment by sahilsingh7735** [comment]
@Dani-Google sure I will assign you a new issue you can work on that.
Can you ping me on a new issue, so I will assign you that.

**Comment by roshan2152** [comment]
HI, can you assign it to me?

**Comment by sahilsingh7735** [comment]
Hi @roshan2152 can you work on the different issue I have assigned this to @ParthasarathiMahana.

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana I have updated the task please look for it.

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana @harsitagarwalla187 @roshan2152 @Dani-Google 
I have updated the issue, so kindly look forward to complete that.

**Comment by ParthasarathiMahana** [comment]
Ok @sahilsingh7735

**Comment by harsitagarwalla187** [comment]
@ParthasarathiMahana I am a beginner.

**Comment by sahilsingh7735** [comment]
@harsitagarwalla187 you can also work on this issue. If you want, you can see another issue as well

**Comment by harsitagarwalla187** [comment]
@sahilsingh7735 ok

**Comment by harsitagarwalla187** [comment]
@sahilsingh7735 Can i use bootstrap?

**Comment by sahilsingh7735** [comment]
@harsitagarwalla187 sure you can you it..

**Comment by ParthasarathiMahana** [comment]
hi @sahilsingh7735 can you please check the Updates I made and tell me if anything else can I do?
Thank you.

**Comment by sahilsingh7735** [comment]
@ParthasarathiMahana can just use git pull and synchronize all the files 
Also raise new PR.

**Comment by Vaishnavi-More** [comment]
Hey @sahilsingh7735, can you assign this to me? 
I am a beginner in open source contribution and I really want to work on it. I have prior experience of web development.
