### ISSUE TITLE
Make a Navigation bar 

### ISSUE THREAD

**Issue by sahilsingh7735** [sahilsingh7735/web#11]
Make a navigation bar, it should contain 

1. left corner random icon.
2. on right side there should be (Home, About, Profile). 
3. on Click any  (Home, About, Profile) page should be redirected to a specific page. 
[See This](https://www.w3schools.com/css/css_navbar.asp)

**Comment by ashishpetwal** [comment]
hey @sahilsingh7735 ! Kindly to assign it to me...

**Comment by its-me-Harsh-Anand** [comment]
Hey @sahilsingh7735 , Please assign this task to me

**Comment by sahilsingh7735** [comment]
@ashishpetwal I will assign you this.

@its-me-Harsh-Anand I will also assign you this.

**Comment by its-me-Harsh-Anand** [comment]
@sahilsingh7735 Please review the code for Navbar

**Comment by Harsh-Tewari** [comment]
> Make a navigation bar, it should contain
> 
>     1. left corner random icon.
> 
>     2. on right side there should be (Home, About, Profile).
> 
>     3. on Click any  (Home, About, Profile) page should be redirected to a specific page.
>        [See This](https://www.w3schools.com/css/css_navbar.asp)

Hey Sahil, I am a web developer, have some experience with making webpages. So I request you to kindly allot this issue to me. I wish to contribute in this Navbar

**Comment by sahilsingh7735** [comment]
@Harsh-Tewari as you have experience, so I would like to give you little good issue.

**Comment by sahilsingh7735** [comment]
.

**Comment by shakti1590** [comment]
Hi Sahil, I want to work on this issue, can you please assign this to me!

**Comment by codin-AWMKAR** [comment]
Hi Sahil, I want to work on this issue as I have recently completed a similar project for my database personal project.
