### ISSUE TITLE
Make an image slider.

### ISSUE THREAD

**Issue by sahilsingh7735** [sahilsingh7735/web#12]
Make an image slider on home page 

1. in the slider there should be images of 7 wonders of the world.
2. below the image, there should be a small description about the image

**Comment by k3yss** [comment]
I can work on this issue, can you assign it to me

**Comment by Milind-Palaria** [comment]
hey @sahilsingh7735 can u assign me this?

**Comment by sahilsingh7735** [comment]
@k3yss I will assign this to you
@Milind-Palaria I will assign you too.

**Comment by Harsh-Tewari** [comment]
Hi Sahil, I want to work on this issue, can you please assign this to me!

**Comment by sahilsingh7735** [comment]
@Harsh-Tewari sure.

**Comment by sahilsingh7735** [comment]
@Milind-Palaria  @k3yss @Harsh-Tewari you have to create a new branch, and then you have to raise a PR.

**Comment by rym-oualha** [comment]
Want to work on this , is it still possible ?

**Comment by shakti1590** [comment]
Hi Sahil, I want to work on this issue, can you please assign this to me!
i have 1+ year experience in web development
