### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by sahilsingh7735** [sahilsingh7735/web#14]
Make an about page and in about page there should be demo detail about the traveler who wish to see 7 wonders of the world.

1. There should be an image.
2. There should be a name.
3. Description about traveler 
4. Places he wanted to visit.
5. Places he has visited.
6. rating the places he has visited.

**Comment by aaushitiwari** [comment]
I want to work on this issue could you please assign it to me.

**Comment by Nincompup** [comment]
@sahilsingh7735  could you assign this to me?

**Comment by sahilsingh7735** [comment]
@aaushitiwari  @Nincompup Sure I will assign you this issue.

**Comment by aaushitiwari** [comment]
@sahilsingh7735 I thought only one person can work on an issue, this would avoid conflicts.

**Comment by Nincompup** [comment]
I'm sorry, but I've completed more than half of the issue

**Comment by Nincompup** [comment]
However, it is not the case that only one person can work on the issue, right?

**Comment by sahilsingh7735** [comment]
@aaushitiwari  @Nincompup I understand your concern, In past experience I have seen that people ask for the issue, and they don't complete it ok, so what I have done is I assigned multiple people to work on the same issue.

As @Nincompup said he has done more than half, So @aaushitiwari I will make new issue so that you can work on it. It will be similar as this was, so there will be no problem.

**Comment by aaushitiwari** [comment]
Okay, no issues. Let me know about the issue. Thank you.

**Comment by sahilsingh7735** [comment]
@aaushitiwari I have created new issue (What to pack page). Ping me there, I will assign you that.

**Comment by sahilsingh7735** [comment]
@Nincompup you have to create a new branch, and then you have to raise a PR.

**Comment by aaushitiwari** [comment]
> @aaushitiwari I have created new issue (What to pack page). Ping me there, I will assign you that.

okay
