### ISSUE TITLE
What to pack page

### ISSUE THREAD

**Issue by sahilsingh7735** [sahilsingh7735/web#18]
Create a new web page name what to "Packing"

List of essential items required.(Heading)
- [See this Link](https://travellersworldwide.com/category/product-reviews/)
- there should be a card and item image and description.

 **Add on**
List Items according to travelers stay 
[Example]

1. Staying in a tent house 
2. Staying in Hostel
3. etc etc...

**Comment by sahilsingh7735** [comment]
You have to create a new branch, and then you have to raise a PR.

**Comment by aaushitiwari** [comment]
Can you assign this issue to me?

**Comment by sahilsingh7735** [comment]
@aaushitiwari sure, go ahead.
And be creative, bring your imagination.
Ensure to cover all the essential items from traveler's perspective.

**Comment by aaushitiwari** [comment]
Can you tell me how many cards you want? or any specific color scheme, or font?

**Comment by sahilsingh7735** [comment]
@aaushitiwari Be creative and use bootstrap, this will help you to build fast.
And there is no specific color scheme, or font, you can use random color.

**Comment by aaushitiwari** [comment]
Okay .

**Comment by aaushitiwari** [comment]
@sahilsingh7735 how many items do you want me to add in a particular section such as tents etc. because the number of things varies. So should I go for 10 items?

**Comment by sahilsingh7735** [comment]
@aaushitiwari ya sure 10 sounds good.

**Comment by aaushitiwari** [comment]
Okay, thanks!

**Comment by aaushitiwari** [comment]
Okay, so I have made 2 stay options and added 10 items each. Do you want me to do anything else or should I raise a PR

**Comment by aaushitiwari** [comment]
Why is it showing excluded?? @sahilsingh7735 
![Screenshot_2022-10-10-23-12-46-37_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/110895038/194924471-7f7a46c2-098d-4743-8c45-ce97a76deec2.jpg)
