### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by sahilsingh7735** [sahilsingh7735/web#19]
Create a "Contact" page. 

In the form this should be there
1. name
2. email
3. message
4. button (Send)

On Click button, the data should be console.log(DATA)
![contact](https://user-images.githubusercontent.com/66689465/193407534-378dfcf5-3186-405e-9b47-183ee1be0478.png)

**Comment by Aman0786-git** [comment]
can you please assign me this

**Comment by Rashmisingh-18** [comment]
Hey, please assign this issue to me?

**Comment by sahilsingh7735** [comment]
@Rashmisingh-18 sure, go ahead.

**Comment by KMayank02** [comment]
Can I work on this? If yes, do you want the same ui as presented above?

**Comment by sahilsingh7735** [comment]
@KMayank02  I have already assigned this task to @Rashmisingh-18 . So @KMayank02 you can see another issue on this issue section.

**Comment by sahilsingh7735** [comment]
@Rashmisingh-18  Use bootstrap for styling.

**Comment by Rashmisingh-18** [comment]
I am done with this issue, please review it so I can make a pull request. Attaching the image.
![Final_Image](https://user-images.githubusercontent.com/90052358/193448498-81d795a3-5ef9-4fee-8055-e8c980fbd23f.png)

**Comment by subhammaji** [comment]
Please assign me this task.
