### ISSUE TITLE
Fixing the index page

### ISSUE THREAD

**Issue by sahilsingh7735** [sahilsingh7735/web#34]
Fix the index page,

**Comment by vedamruta** [comment]
Hey, I will try to fix the page. Please assign this issue to me :)

**Comment by vedamruta** [comment]
I ain't understanding what you want on the index.html page ?? Because I saw your repo, it already has sevenwonders.html file in which you tried to display seven wonders. Do I need to display Caraousel of 7 wonders' pictures  on the index.html page ??

**Comment by DHRUVKHANDELWAL00** [comment]
hey @sahilsingh7735 , please assign it to me.

**Comment by bilalshaikh292** [comment]
heyy @sahilsingh7735  is the issue still open I would like to contribute?

**Comment by apoorv654123** [comment]
if the issue is open i am trying to **contribute** in it
