### ISSUE TITLE
Convert HTML to react

### ISSUE THREAD

**Issue by sahilsingh7735** [sahilsingh7735/web#37]
Convert HTML to react with react-router implementation.

**Comment by vanshika8750** [comment]
i can do it. please assign it to me

**Comment by sahilsingh7735** [comment]
@vanshika8750  sure go ahead.

**Comment by sahilsingh7735** [comment]
@vanshika8750   Just a reminder make a separate branch then raise a PR and take a pull before raising PR.

**Comment by harshoo1** [comment]
@sahilsingh7735  i can do this task easily

**Comment by harshoo1** [comment]
@sahilsingh7735  sir i can do your task easily, please assign it to me if possible

**Comment by sahilsingh7735** [comment]
@harshoo1 sure go ahead

**Comment by parthivghose2919** [comment]
@harshoo1 sir can i do this task ...i have started working on this ..can you please assign me with this issue...Thank you!!!

**Comment by sahilsingh7735** [comment]
Resolved.
